import type { WeeklyMeal } from "./types";

export const weeklyMeals: WeeklyMeal[] = [
  {
    weekdayShort: "Mo",
    weekdayShortEn: "Mon",
    date: 12,
    emoji: "🍝",
    name: "Spaghetti Bolognese",
    nameEn: "Spaghetti Bolognese",
    durationMin: 30,
    isToday: false,
  },
  {
    weekdayShort: "Di",
    weekdayShortEn: "Tue",
    date: 13,
    emoji: "🥗",
    name: "Hähnchen-Salat",
    nameEn: "Chicken salad",
    durationMin: 20,
    isToday: false,
  },
  {
    weekdayShort: "Mi",
    weekdayShortEn: "Wed",
    date: 14,
    emoji: "🍛",
    name: "Kürbis-Risotto",
    nameEn: "Pumpkin risotto",
    durationMin: 35,
    isToday: true,
  },
  {
    weekdayShort: "Do",
    weekdayShortEn: "Thu",
    date: 15,
    emoji: "🌮",
    name: "Tacos für alle",
    nameEn: "Tacos for everyone",
    durationMin: 25,
    isToday: false,
  },
  {
    weekdayShort: "Fr",
    weekdayShortEn: "Fri",
    date: 16,
    emoji: "🍕",
    name: "Pizza-Freitag",
    nameEn: "Pizza Friday",
    durationMin: 40,
    isToday: false,
  },
  {
    weekdayShort: "Sa",
    weekdayShortEn: "Sat",
    date: 17,
    emoji: "🐟",
    name: "Lachs mit Reis",
    nameEn: "Salmon & rice",
    durationMin: 30,
    isToday: false,
  },
  {
    weekdayShort: "So",
    weekdayShortEn: "Sun",
    date: 18,
    emoji: "🍲",
    name: "Hühnersuppe Oma",
    nameEn: "Grandma's soup",
    durationMin: 60,
    isToday: false,
  },
];
