// Generated by mcp__supabase__generate_typescript_types
// DO NOT EDIT — re-generate via MCP after schema migrations.
// Spec: docs/superpowers/specs/2026-05-29-supabase-schema-design.md

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      children: {
        Row: {
          allergies: string[];
          birthday: string;
          color: string;
          created_at: string;
          dislikes: string[];
          family_id: string;
          grade: string | null;
          id: string;
          intolerances: string[];
          likes: string[];
          name: string;
          school: string | null;
          updated_at: string;
        };
        Insert: {
          allergies?: string[];
          birthday: string;
          color: string;
          created_at?: string;
          dislikes?: string[];
          family_id: string;
          grade?: string | null;
          id?: string;
          intolerances?: string[];
          likes?: string[];
          name: string;
          school?: string | null;
          updated_at?: string;
        };
        Update: {
          allergies?: string[];
          birthday?: string;
          color?: string;
          created_at?: string;
          dislikes?: string[];
          family_id?: string;
          grade?: string | null;
          id?: string;
          intolerances?: string[];
          likes?: string[];
          name?: string;
          school?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "children_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      event_exceptions: {
        Row: {
          action: Database["public"]["Enums"]["event_exception_action_enum"];
          created_at: string;
          event_id: string;
          id: string;
          occurrence_date: string;
          override: Json | null;
        };
        Insert: {
          action: Database["public"]["Enums"]["event_exception_action_enum"];
          created_at?: string;
          event_id: string;
          id?: string;
          occurrence_date: string;
          override?: Json | null;
        };
        Update: {
          action?: Database["public"]["Enums"]["event_exception_action_enum"];
          created_at?: string;
          event_id?: string;
          id?: string;
          occurrence_date?: string;
          override?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: "event_exceptions_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
        ];
      };
      event_types: {
        Row: {
          color: string;
          created_at: string;
          family_id: string | null;
          icon: string;
          id: string;
          label: Json;
          slug: string;
        };
        Insert: {
          color: string;
          created_at?: string;
          family_id?: string | null;
          icon: string;
          id?: string;
          label: Json;
          slug: string;
        };
        Update: {
          color?: string;
          created_at?: string;
          family_id?: string | null;
          icon?: string;
          id?: string;
          label?: Json;
          slug?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_types_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      events: {
        Row: {
          all_day: boolean;
          child_id: string | null;
          created_at: string;
          created_by: string | null;
          description: string | null;
          end_at: string;
          family_id: string;
          id: string;
          location: string | null;
          rrule_byweekday: number[] | null;
          rrule_count: number | null;
          rrule_freq: Database["public"]["Enums"]["rrule_freq_enum"] | null;
          rrule_interval: number;
          rrule_until: string | null;
          start_at: string;
          title: string;
          type_id: string;
          updated_at: string;
        };
        Insert: {
          all_day?: boolean;
          child_id?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          end_at: string;
          family_id: string;
          id?: string;
          location?: string | null;
          rrule_byweekday?: number[] | null;
          rrule_count?: number | null;
          rrule_freq?: Database["public"]["Enums"]["rrule_freq_enum"] | null;
          rrule_interval?: number;
          rrule_until?: string | null;
          start_at: string;
          title: string;
          type_id: string;
          updated_at?: string;
        };
        Update: {
          all_day?: boolean;
          child_id?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          end_at?: string;
          family_id?: string;
          id?: string;
          location?: string | null;
          rrule_byweekday?: number[] | null;
          rrule_count?: number | null;
          rrule_freq?: Database["public"]["Enums"]["rrule_freq_enum"] | null;
          rrule_interval?: number;
          rrule_until?: string | null;
          start_at?: string;
          title?: string;
          type_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_child_id_fkey";
            columns: ["child_id"];
            isOneToOne: false;
            referencedRelation: "children";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_type_id_fkey";
            columns: ["type_id"];
            isOneToOne: false;
            referencedRelation: "event_types";
            referencedColumns: ["id"];
          },
        ];
      };
      families: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          settings: Json;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          settings?: Json;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          settings?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      family_invitations: {
        Row: {
          created_at: string;
          created_by: string | null;
          expires_at: string;
          family_id: string;
          token: string;
          used_at: string | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          expires_at?: string;
          family_id: string;
          token?: string;
          used_at?: string | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          expires_at?: string;
          family_id?: string;
          token?: string;
          used_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "family_invitations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "family_invitations_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      meal_plan_entries: {
        Row: {
          created_at: string;
          created_by: string | null;
          date: string;
          family_id: string;
          id: string;
          meal_slot: Database["public"]["Enums"]["meal_slot_enum"];
          notes: string | null;
          recipe_id: string;
          servings_override: number | null;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          date: string;
          family_id: string;
          id?: string;
          meal_slot: Database["public"]["Enums"]["meal_slot_enum"];
          notes?: string | null;
          recipe_id: string;
          servings_override?: number | null;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          date?: string;
          family_id?: string;
          id?: string;
          meal_slot?: Database["public"]["Enums"]["meal_slot_enum"];
          notes?: string | null;
          recipe_id?: string;
          servings_override?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "meal_plan_entries_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_plan_entries_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_plan_entries_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      parents: {
        Row: {
          allergies: string[];
          auth_user_id: string;
          color: string;
          created_at: string;
          dislikes: string[];
          family_id: string;
          id: string;
          intolerances: string[];
          likes: string[];
          locale: string;
          name: string;
          short: string;
          updated_at: string;
        };
        Insert: {
          allergies?: string[];
          auth_user_id: string;
          color: string;
          created_at?: string;
          dislikes?: string[];
          family_id: string;
          id?: string;
          intolerances?: string[];
          likes?: string[];
          locale?: string;
          name: string;
          short: string;
          updated_at?: string;
        };
        Update: {
          allergies?: string[];
          auth_user_id?: string;
          color?: string;
          created_at?: string;
          dislikes?: string[];
          family_id?: string;
          id?: string;
          intolerances?: string[];
          likes?: string[];
          locale?: string;
          name?: string;
          short?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "parents_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      recipes: {
        Row: {
          contains_allergens: string[];
          created_at: string;
          created_by_family_id: string | null;
          description: Json | null;
          diet_tags: string[];
          difficulty: string | null;
          duration_min: number | null;
          fetched_at: string;
          id: string;
          image_url: string | null;
          ingredients: Json;
          instructions: Json;
          keywords: string[];
          recipe_dedup_hash: string;
          servings: number | null;
          source: Database["public"]["Enums"]["recipe_source_enum"];
          source_external_id: string | null;
          source_url: string | null;
          title: Json;
        };
        Insert: {
          contains_allergens?: string[];
          created_at?: string;
          created_by_family_id?: string | null;
          description?: Json | null;
          diet_tags?: string[];
          difficulty?: string | null;
          duration_min?: number | null;
          fetched_at?: string;
          id?: string;
          image_url?: string | null;
          ingredients: Json;
          instructions: Json;
          keywords?: string[];
          recipe_dedup_hash: string;
          servings?: number | null;
          source: Database["public"]["Enums"]["recipe_source_enum"];
          source_external_id?: string | null;
          source_url?: string | null;
          title: Json;
        };
        Update: {
          contains_allergens?: string[];
          created_at?: string;
          created_by_family_id?: string | null;
          description?: Json | null;
          diet_tags?: string[];
          difficulty?: string | null;
          duration_min?: number | null;
          fetched_at?: string;
          id?: string;
          image_url?: string | null;
          ingredients?: Json;
          instructions?: Json;
          keywords?: string[];
          recipe_dedup_hash?: string;
          servings?: number | null;
          source?: Database["public"]["Enums"]["recipe_source_enum"];
          source_external_id?: string | null;
          source_url?: string | null;
          title?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "recipes_created_by_family_id_fkey";
            columns: ["created_by_family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      reminders: {
        Row: {
          created_at: string;
          event_id: string | null;
          family_id: string;
          id: string;
          offset_minutes: number;
          recipient_parent_id: string | null;
          sent_at: string | null;
          task_id: string | null;
        };
        Insert: {
          created_at?: string;
          event_id?: string | null;
          family_id: string;
          id?: string;
          offset_minutes: number;
          recipient_parent_id?: string | null;
          sent_at?: string | null;
          task_id?: string | null;
        };
        Update: {
          created_at?: string;
          event_id?: string | null;
          family_id?: string;
          id?: string;
          offset_minutes?: number;
          recipient_parent_id?: string | null;
          sent_at?: string | null;
          task_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "reminders_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reminders_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reminders_recipient_parent_id_fkey";
            columns: ["recipient_parent_id"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reminders_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
        ];
      };
      task_types: {
        Row: {
          color: string;
          created_at: string;
          family_id: string | null;
          icon: string;
          id: string;
          label: Json;
          slug: string;
        };
        Insert: {
          color: string;
          created_at?: string;
          family_id?: string | null;
          icon: string;
          id?: string;
          label: Json;
          slug: string;
        };
        Update: {
          color?: string;
          created_at?: string;
          family_id?: string | null;
          icon?: string;
          id?: string;
          label?: Json;
          slug?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_types_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          child_id: string | null;
          completed_at: string | null;
          completed_by: string | null;
          created_at: string;
          created_by: string | null;
          description: string | null;
          due_date: string;
          due_time: string | null;
          family_id: string;
          id: string;
          is_done: boolean;
          subject: string | null;
          title: string;
          type_id: string;
          updated_at: string;
        };
        Insert: {
          child_id?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          due_date: string;
          due_time?: string | null;
          family_id: string;
          id?: string;
          is_done?: boolean;
          subject?: string | null;
          title: string;
          type_id: string;
          updated_at?: string;
        };
        Update: {
          child_id?: string | null;
          completed_at?: string | null;
          completed_by?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string | null;
          due_date?: string;
          due_time?: string | null;
          family_id?: string;
          id?: string;
          is_done?: boolean;
          subject?: string | null;
          title?: string;
          type_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_child_id_fkey";
            columns: ["child_id"];
            isOneToOne: false;
            referencedRelation: "children";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_completed_by_fkey";
            columns: ["completed_by"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "parents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_family_id_fkey";
            columns: ["family_id"];
            isOneToOne: false;
            referencedRelation: "families";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_type_id_fkey";
            columns: ["type_id"];
            isOneToOne: false;
            referencedRelation: "task_types";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_invitation: {
        Args: {
          p_color: string;
          p_parent_name: string;
          p_short: string;
          p_token: string;
        };
        Returns: string;
      };
      create_family: {
        Args: {
          p_color: string;
          p_family_name: string;
          p_parent_name: string;
          p_short: string;
        };
        Returns: string;
      };
      current_family_id: { Args: never; Returns: string };
    };
    Enums: {
      event_exception_action_enum: "cancelled" | "modified";
      meal_slot_enum: "breakfast" | "lunch" | "dinner" | "snack";
      recipe_source_enum: "gustar_generated" | "gustar_searched" | "gustar_crawled" | "user_custom";
      rrule_freq_enum: "daily" | "weekly" | "monthly" | "yearly";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      event_exception_action_enum: ["cancelled", "modified"],
      meal_slot_enum: ["breakfast", "lunch", "dinner", "snack"],
      recipe_source_enum: ["gustar_generated", "gustar_searched", "gustar_crawled", "user_custom"],
      rrule_freq_enum: ["daily", "weekly", "monthly", "yearly"],
    },
  },
} as const;
